# Generated by Django 4.2.17 on 2024-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hulchullapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretcodedb',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
