# Generated by Django 4.2.17 on 2024-12-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
