# Generated by Django 4.2.17 on 2024-12-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfoapp', '0002_alter_highlights_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='ender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
